### PR TITLE
Fix typos and grammar

### PR DESCRIPTION
**Pull request by blorente**

### CODE REVIEW

**Comment by ferreiro** [comment]
Hi @blorente. Thanks for your suggestions. Have some feedback on the "Team" Section:
- I think is a good idea to talk about the software we write: Reliable, Testable, Fast, Rock Solid.

What about:
"Our development process is driven by Agile principles to provide value quickly, so you can enjoy our features as soon as possible. The code We write is reliable, safely and testable."

**Comment by blorente** [comment]
Actually, for the end users, they don't care the we use TDD, I don'n think it's relevant that we build testable software. 
However, I like the idea about "solid products", will give it another spin later.

**Comment by ferreiro** [comment]
I partially agree with that argument. Why don't tell the clients how we work? This is part of our culture of work!

I agree that the "testable part" is not so important. But, the fact that We write fast, reliable and rock solid code is something clients care about.

**Comment by ferreiro** [comment]
We should tell the clients how we actually work.
This kind of things is part of our culture of work, so I think is important to include it.

I agree that the "testable part" is not so relevant. But, the fact that We write fast, reliable and rock solid code is something clients care about and also is a good thing to tell here :)

**Comment by blorente** [comment]
Take a look at it now, see if you like it better :)

**Comment by ferreiro** [comment]
Better now! 
Just 2 slightly modified version. Tell me what you think:

a) "We use Agile practices to deliver a rock-solid and reliable product. Our development process let us develop new functionalities quickly so you can enjoy new updates very often."
b) "We use Agile practices to deliver a rock-solid and reliable product <strong>quickly</strong>, so you can enjoy new features very often."

**Comment by ferreiro** [comment]
Better now! 
Only two slight modifications. Tell me what you think:

a) "We use Agile practices to deliver a rock-solid and reliable product. Our development process let us develop functionalities quickly so you can enjoy new updates very often."
b) "We use Agile practices to deliver a rock-solid and reliable product quickly, so you can enjoy new features very often."

**Comment by blorente** [comment]
Squashed

**Comment by ferreiro** [comment]
Merged :)

**Pull request merged**
